### PR TITLE
Arena::alloc_with_id

### PR DESCRIPTION
**Pull request by fitzgen**
+cc @alexcrichton

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]

**Comment by alexcrichton** [comment]
Hm so one thing I ran into transitioning, I'm not sure how we'd implement `insert_with_id` [around here](https://github.com/rustwasm/walrus/blob/7969f8028014f4328fa937ca41ab8bee3376c915/src/arena_set.rs#L31-L45).

**Comment by fitzgen** [comment]
> Hm so one thing I ran into transitioning, I'm not sure how we'd implement `insert_with_id` [around here](https://github.com/rustwasm/walrus/blob/7969f8028014f4328fa937ca41ab8bee3376c915/src/arena_set.rs#L31-L45).

Right because we couldn't construct the value to check whether it is already in the set without potentially adding duplicates.

I can make `Arena::next_id` public again, and then this wouldn't be a breaking change either... sound good?

**Comment by matklad** [comment]
How that API is actually used? It is a sort of self-fulfilling proficy: if you construct an entity with a fresh id, it wouldn’t be in the set. If this is expected behavior, perhaps that could could change it’s next_id to with_id as well?

**Comment by fitzgen** [comment]
> How that API is actually used?

It is used by things whose equality/hash don't depend on the `Id`, for when we would like to de-duplicate items with a set whose storage is ultimately backed by an arena.

For example, function type declartations (which are separated and de-duped from the functions themselves): https://github.com/rustwasm/walrus/blob/ce985f826c89d2cc8e56e0d00b0a47c83bbd83af/src/module/types.rs#L56

**Comment by alexcrichton** [comment]
Leaving `next_id` is fine by me yeah!

**Pull request merged**
