### PR TITLE
Make Eq and Hash consistent

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Review by fitzgen — APPROVED** [review]
Good catch!

**Comment by fitzgen** [comment]
Published 1.0.2 with these two PRs -- thanks again!

**Comment by matklad** [comment]
Awesome! WDYT about https://github.com/fitzgen/id-arena/issues/1 though? If I can use plain `u32` for indexing, I'll be able to get rid of my hand-written impl here: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_analysis/src/arena.rs :)

**Comment by fitzgen** [comment]
Writing up a reply / thinking about design now.

**Comment by matklad** [comment]
>I'll be able to get rid of my hand-written impl here: 

Hm, I've remembered one thing that probably require me to stick with my implementation. I really need `Arena` to be `Eq` because I use it with [salsa](http://github.com/salsa-rs/salsa). However, due to `arena_id`, arenas will never be equal.

**Pull request merged**
