### PR TITLE
Some little things

### PR DESCRIPTION
**Pull request by fitzgen**
As I use this crate, I've needed these little things.

### CODE REVIEW

**Review by matklad — APPROVED** [review]
👍

**Comment by matklad** [comment]
FWIW, i’ve switched to a hand-written arena for rust analyzer. I found it convenient to be able to use different Id structs for different arenas instead of generic Id<T>: this gives you nice Debug, is more flexible for coherence and make it more obvious which ID is used with which arena: Arena<Expr, ExprData>. 

https://github.com/rust-analyzer/rust-analyzer/blob/c0f48f9eb091b5054acb98575c69c67a0aeefb7b/crates/ra_arena/src/lib.rs#L63

**Comment by fitzgen** [comment]
> FWIW, i’ve switched to a hand-written arena for rust analyzer. I found it convenient to be able to use different Id structs for different arenas instead of generic Id: this gives you nice Debug, is more flexible for coherence and make it more obvious which ID is used with which arena: Arena<Expr, ExprData>.

Cool -- do you want me to stop flagging you for review on PRs for this crate then?

**Comment by matklad** [comment]
>Cool -- do you want me to stop flagging you for review on PRs for this crate then?

No, I'll be glad to do reviews! :)

**Pull request merged**
